import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
const inter = Inter({ subsets: ["latin"] });
import { UserProvider } from "./context/UserContext";
import Flow from "./components/Flow";
import { FlowContextProvider } from "./context/FlowContext";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        <Navbar merchantName="Groww" merchantLogo="./CardLogo.jpeg" />
        <UserProvider>
          <FlowContextProvider>
            <Flow />
            {children}
          </FlowContextProvider >
        </UserProvider>
      </body>
    </html>
  );
}

